print('-'*40)
print('Tugas 1 SISOP Kelas-A')
print('-'*40)
print('Nama : Abdul Mukti')
print('NPM  : 21083010098')
print('-'*40)
print('notes:')
print('-'*40)
print('halo dunia!')
print('ini adalah skrip Bash pertamaku di Linux')
