echo "------------------------------------------"
echo "Tugas 1 SISOP Kelas-A"
echo "------------------------------------------"
echo "Nama : Abdul Mukti"
echo " NPM  : 21083010098"
echo "------------------------------------------"
echo "notes"
echo "------------------------------------------"
echo "halo dunia!"
echo "ini adalah skrip Bash pertamaku di Linux"
